## 0.2.1 (2024-10-29)

- handled connection error properly (as promise rejection)


## 0.2.0 (2024-03-17)

**Incompatible changes**

- changed `rpc.call` and `rpc.call_async` to return bytes instead of python
  dicts/lists


## 0.1.0

Initial version.
